### Lendo o DataFrame com as casas a preficicar

In [2]:
import pandas as pd

In [7]:
casas = pd.read_csv("C:/Users/augus/OneDrive/Documentos/Data Science/Regressão linear - Transformando variavies/casas_a_precificar.csv")

In [8]:
casas.head()

   area_primeiro_andar  existe_segundo_andar  area_quintal  dist_metro
0                  180                     1            40         8.0
1                  130                     0            80         1.0
2                  170                     1            60         7.5
3                  250                     1            70         4.0
4                  260                     0            70         8.5

In [11]:
casas.columns = ['log_area_primeiro_andar', 'existe_segundo_andar', 'log_area_quintal', 'log_dist_metro']

In [12]:
import numpy as np

In [13]:
casas['log_area_primeiro_andar'] = np.log(dados['area_primeiro_andar'])
casas['log_area_quintal'] = np.log1p(dados['area_quintal'])
casas['log_dist_metro'] = np.log(dados['dist_metro'])

In [14]:
casas

,log_area_primeiro_andar,existe_segundo_andar,log_area_quintal,log_dist_metro
0,5.192957,1,3.713572,2.079442
1,4.867534,0,4.394449,0.000000
2,5.135798,1,4.110874,2.014903
3,5.521461,1,4.262680,1.386294
4,5.560682,0,4.262680,2.140066
5,5.298317,0,4.948760,0.405465
6,5.703782,0,4.948760,1.609438
7,4.787492,0,4.110874,2.302585
8,4.787492,1,4.615121,0.405465
9,4.787492,1,3.713572,2.014903

### Importando o modelo salvo em pickle

In [15]:
import pickle

In [19]:
m = open("C:/Users/augus/OneDrive/Documentos/Data Science/Regressão linear - Transformando variavies/modelos_casa_a_preficicar.pkl", "rb")
modelo = pickle.load(m)
m.close()

### Estimando o modelo das casas

In [20]:
previsao_precos = modelo.predict(casas)

In [26]:
previsao_precos

array([13.7089794 , 13.95497022, 13.72879066, 14.09743924, 13.73265545,
       14.10842228, 13.99698273, 13.29196957, 14.0145501 , 13.52325782])

In [27]:
for i in range(len(previsao_precos)):
    precos_convertidos = np.exp(previsao_precos)

In [37]:
casas.drop(columns = 'valor', inplace=True)

In [39]:
casas.insert(0, 'valor', precos_convertidos)

In [40]:
casas

,valor,log_area_primeiro_andar,existe_segundo_andar,log_area_quintal,log_dist_metro
0,8.989470e+05,5.192957,1,3.713572,2.079442
1,1.149652e+06,4.867534,0,4.394449,0.000000
2,9.169339e+05,5.135798,1,4.110874,2.014903
3,1.325684e+06,5.521461,1,4.262680,1.386294
4,9.204845e+05,5.560682,0,4.262680,2.140066
5,1.340324e+06,5.298317,0,4.948760,0.405465
6,1.198981e+06,5.703782,0,4.948760,1.609438
7,5.924191e+05,4.787492,0,4.110874,2.302585
8,1.220230e+06,4.787492,1,4.615121,0.405465
9,7.465798e+05,4.787492,1,3.713572,2.014903

In [41]:
casas['preco_formatado'] = casas['valor'].apply(lambda x: f"{x:,.2f}")

,valor,log_area_primeiro_andar,existe_segundo_andar,log_area_quintal,log_dist_metro,preco_formatado
0,8.989470e+05,5.192957,1,3.713572,2.079442,"898,947.04"
1,1.149652e+06,4.867534,0,4.394449,0.000000,"1,149,652.43"
2,9.169339e+05,5.135798,1,4.110874,2.014903,"916,933.89"
3,1.325684e+06,5.521461,1,4.262680,1.386294,"1,325,684.17"
4,9.204845e+05,5.560682,0,4.262680,2.140066,"920,484.50"
5,1.340324e+06,5.298317,0,4.948760,0.405465,"1,340,324.47"
6,1.198981e+06,5.703782,0,4.948760,1.609438,"1,198,981.17"
7,5.924191e+05,4.787492,0,4.110874,2.302585,"592,419.08"
8,1.220230e+06,4.787492,1,4.615121,0.405465,"1,220,230.22"
9,7.465798e+05,4.787492,1,3.713572,2.014903,"746,579.82"